name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  PROJECT_ID: project-c2023f82-4f20-4fee-b94
  REGION: us-central1

  REPOSITORY: realestate-repo
  SERVICE_NAME: realestate
  IMAGE_NAME: realestate

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # ✅ OIDC authentication
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/68321934190/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@project-c2023f82-4f20-4fee-b94.iam.gserviceaccount.com

      # ✅ install gcloud only
      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 470.0.0"

      # ✅ docker auth does NOT refresh token
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build -t \
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push image
        run: |
          docker push \
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --project=${{ env.PROJECT_ID }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --port=8501 \
            --memory=4Gi \
            --timeout=900 \
            --max-instances=3
