name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  PROJECT_ID: project-c2023f82-4f20-4fee-b94
  REGION: us-central1
  REPOSITORY: realestate-repo
  SERVICE_NAME: realestate
  IMAGE_NAME: realestate

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # ⭐ REQUIRED for Workload Identity Federation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ KEYLESS AUTHENTICATION
      - name: Authenticate to Google Cloud (WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/68321934190/locations/global/workloadIdentityPools/mlops-pool/providers/github-provider"
          service_account: "mlops-sa@project-c2023f82-4f20-4fee-b94.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker \
          ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t \
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: |
          docker push \
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --port=8501 \
            --memory=4Gi \
            --timeout=900 \
            --max-instances=3 \
            --project=${{ env.PROJECT_ID }} \
            --set-env-vars GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}"
